version: '3.8'

services:
  trinity-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NAS_TYPE=${NAS_TYPE}
      - NAS_URL=${NAS_URL}
      - NAS_USERNAME=${NAS_USERNAME}
      - NAS_PASSWORD=${NAS_PASSWORD}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - trinity-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=trinity
      - POSTGRES_PASSWORD=trinity_password
      - POSTGRES_DB=trinity_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trinity-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - trinity-network

volumes:
  postgres_data:
  n8n_data:

networks:
  trinity-network:
    driver: bridge